Update 01-building-blocks.yaml

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,9 +12,8 @@ jobs:
     runs-on: ubuntu-latest
     steps: 
       - name: Failed step
-        run: 
-        echo "I will fail"
-        exit 1
+      - run: echo "I will fail"
+             exit 1
 
       - name: Say goodbye
         echo: "Goodbye"
